import fs from 'fs';
import path from 'path';

// 24 Official Jeeliz Models with exact SKUs, shapes, materials, and transparent overlay assets
const jeelizCatalog = [
  {
    sku: "rayban_aviator_or_vertFlash",
    name: "Ray-Ban RB3025 Aviator Gold / Classic Green",
    brand: "Ray-Ban",
    shape: "aviator",
    frame_type: "Full Rim",
    size_category: "Wide",
    material: "Arista Gold Metal",
    price_inr: 7490,
    category: "sunglasses",
    gender: "unisex",
    color: "#d4af37",
    rating: 4.9,
    reviews_count: 32400,
    target_face_shapes: ["Square", "Heart", "Oval"],
    image: "/frames/frame1.jpg",
    framePng: "/frames/jj-aviator-gold-polarized-21.png",
    dimensions: { lens_width_mm: 58, bridge_width_mm: 14, temple_length_mm: 140, frame_width_mm: 140 }
  },
  {
    sku: "rayban_wayfarer_havane_vert",
    name: "Ray-Ban Original Wayfarer Havana Tortoise",
    brand: "Ray-Ban",
    shape: "wayfarer",
    frame_type: "Full Rim",
    size_category: "Medium",
    material: "Handmade Acetate",
    price_inr: 6890,
    category: "sunglasses",
    gender: "unisex",
    color: "#78350f",
    rating: 4.8,
    reviews_count: 28900,
    target_face_shapes: ["Round", "Oval", "Heart"],
    image: "/frames/frame2.jpg",
    framePng: "/frames/vc-wayfarer-classic-black-30.png",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 22, temple_length_mm: 150, frame_width_mm: 142 }
  },
  {
    sku: "rayban_round_gun_vert",
    name: "Ray-Ban RB3447 Round Metal Gunmetal",
    brand: "Ray-Ban",
    shape: "round",
    frame_type: "Full Rim",
    size_category: "Medium",
    material: "Gunmetal Titanium",
    price_inr: 6990,
    category: "sunglasses",
    gender: "unisex",
    color: "#475569",
    rating: 4.9,
    reviews_count: 19400,
    target_face_shapes: ["Square", "Rectangle", "Diamond"],
    image: "/frames/frame3.jpg",
    framePng: "/frames/air-round-silver-rimless-08.png",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 21, temple_length_mm: 145, frame_width_mm: 135 }
  },
  {
    sku: "rayban_clubmaster_noir_bleuGris",
    name: "Ray-Ban Clubmaster Classic Black & Gold",
    brand: "Ray-Ban",
    shape: "clubmaster",
    frame_type: "Half Rim",
    size_category: "Medium",
    material: "Acetate & Metal",
    price_inr: 7290,
    category: "sunglasses",
    gender: "unisex",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 24100,
    target_face_shapes: ["Round", "Oval", "Heart"],
    image: "/frames/frame4.jpg",
    framePng: "/frames/vc-clubmaster-black-gold-25.png",
    dimensions: { lens_width_mm: 51, bridge_width_mm: 21, temple_length_mm: 145, frame_width_mm: 139 }
  },
  {
    sku: "rayban_round_or_vert",
    name: "Ray-Ban Round Vintage Gold Mirror G-15",
    brand: "Ray-Ban",
    shape: "round",
    frame_type: "Full Rim",
    size_category: "Narrow",
    material: "Polished Gold Wire",
    price_inr: 6590,
    category: "sunglasses",
    gender: "women",
    color: "#d4af37",
    rating: 4.7,
    reviews_count: 15300,
    target_face_shapes: ["Square", "Rectangle"],
    image: "/frames/frame5.jpg",
    framePng: "/frames/air-round-gold-05.png",
    dimensions: { lens_width_mm: 48, bridge_width_mm: 20, temple_length_mm: 140, frame_width_mm: 132 }
  },
  {
    sku: "rayban_justin_noir_bleuMirroir",
    name: "Ray-Ban Justin Matte Black / Mirror Blue",
    brand: "Ray-Ban",
    shape: "square",
    frame_type: "Full Rim",
    size_category: "Wide",
    material: "Rubberized TR90",
    price_inr: 5990,
    category: "sunglasses",
    gender: "men",
    color: "#0284c7",
    rating: 4.8,
    reviews_count: 31200,
    target_face_shapes: ["Round", "Oval"],
    image: "/frames/frame6.jpg",
    framePng: "/frames/jj-square-matte-navy-14.png",
    dimensions: { lens_width_mm: 55, bridge_width_mm: 16, temple_length_mm: 145, frame_width_mm: 144 }
  },
  {
    sku: "rayban_erika_marronArgent_marronVioletDegrade",
    name: "Ray-Ban Erika Velvet Brown & Silver",
    brand: "Ray-Ban",
    shape: "cat-eye",
    frame_type: "Full Rim",
    size_category: "Medium",
    material: "Velvet Acetate & Metal",
    price_inr: 6190,
    category: "sunglasses",
    gender: "women",
    color: "#78350f",
    rating: 4.9,
    reviews_count: 18400,
    target_face_shapes: ["Round", "Square", "Heart"],
    image: "/frames/frame7.jpg",
    framePng: "/frames/vc-cateye-black-17.png",
    dimensions: { lens_width_mm: 54, bridge_width_mm: 18, temple_length_mm: 145, frame_width_mm: 138 }
  },
  {
    sku: "rayban_predator_noir_vert_classique",
    name: "Ray-Ban Predator 2 Sport Black Rectangle",
    brand: "Ray-Ban",
    shape: "rectangle",
    frame_type: "Full Rim",
    size_category: "Wide",
    material: "Impact Polycarbonate",
    price_inr: 5790,
    category: "sunglasses",
    gender: "men",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 16200,
    target_face_shapes: ["Round", "Oval"],
    image: "/frames/frame8.jpg",
    framePng: "/frames/vc-rectangle-black-01.png",
    dimensions: { lens_width_mm: 62, bridge_width_mm: 15, temple_length_mm: 135, frame_width_mm: 145 }
  },
  {
    sku: "rayban_cockpit_or_vert_classique",
    name: "Ray-Ban Cockpit Pilot Arista Gold",
    brand: "Ray-Ban",
    shape: "aviator",
    frame_type: "Full Rim",
    size_category: "Medium",
    material: "Monel Alloy",
    price_inr: 7890,
    category: "sunglasses",
    gender: "men",
    color: "#d4af37",
    rating: 4.8,
    reviews_count: 12800,
    target_face_shapes: ["Square", "Heart", "Oval"],
    image: "/frames/frame9.jpg",
    framePng: "/frames/air-aviator-silver-optical-23.png",
    dimensions: { lens_width_mm: 56, bridge_width_mm: 15, temple_length_mm: 140, frame_width_mm: 138 }
  },
  {
    sku: "rayban_clubround_noir_vertClassique_g15",
    name: "Ray-Ban Clubround Jet Black / G-15",
    brand: "Ray-Ban",
    shape: "geometric",
    frame_type: "Half Rim",
    size_category: "Medium",
    material: "Acetate & Metal",
    price_inr: 7490,
    category: "sunglasses",
    gender: "unisex",
    color: "#0f172a",
    rating: 4.9,
    reviews_count: 14700,
    target_face_shapes: ["Square", "Oval"],
    image: "/frames/frame10.jpg",
    framePng: "/frames/jj-geometric-black-10.png",
    dimensions: { lens_width_mm: 51, bridge_width_mm: 19, temple_length_mm: 140, frame_width_mm: 137 }
  },
  {
    sku: "rayban_boyfriend_noir_marron_degrade",
    name: "Ray-Ban Boyfriend Oversized Bold Square",
    brand: "Ray-Ban",
    shape: "square",
    frame_type: "Full Rim",
    size_category: "Extra Wide",
    material: "Premium Acetate",
    price_inr: 6890,
    category: "sunglasses",
    gender: "unisex",
    color: "#0f172a",
    rating: 4.7,
    reviews_count: 11900,
    target_face_shapes: ["Round", "Oval"],
    image: "/frames/frame11.jpg",
    framePng: "/frames/vc-square-hustlr-13.png",
    dimensions: { lens_width_mm: 60, bridge_width_mm: 15, temple_length_mm: 145, frame_width_mm: 148 }
  },
  {
    sku: "rayban_chris_havane_gun_vert_classique",
    name: "Ray-Ban Chris Tortoise & Gunmetal",
    brand: "Ray-Ban",
    shape: "wayfarer",
    frame_type: "Full Rim",
    size_category: "Medium",
    material: "Rubberized Tortoise",
    price_inr: 5990,
    category: "sunglasses",
    gender: "unisex",
    color: "#b45309",
    rating: 4.8,
    reviews_count: 21300,
    target_face_shapes: ["Round", "Oval", "Heart"],
    image: "/frames/frame12.jpg",
    framePng: "/frames/ojos-wayfarer-tortoise-amber-32.png",
    dimensions: { lens_width_mm: 54, bridge_width_mm: 18, temple_length_mm: 145, frame_width_mm: 140 }
  },
  {
    sku: "rayban_round_cuivre_pinkBrownDegrade",
    name: "Ray-Ban Round Copper Pink-Brown Gradient",
    brand: "Ray-Ban",
    shape: "round",
    frame_type: "Full Rim",
    size_category: "Medium",
    material: "Copper Steel",
    price_inr: 7190,
    category: "sunglasses",
    gender: "women",
    color: "#fb7185",
    rating: 4.9,
    reviews_count: 9800,
    target_face_shapes: ["Square", "Rectangle"],
    image: "/frames/frame1.jpg",
    framePng: "/frames/air-geometric-rose-gold-12.png",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 21, temple_length_mm: 145, frame_width_mm: 136 }
  },
  {
    sku: "rayban_justin_noir_rougeMirroir",
    name: "Ray-Ban Justin Rubber Black / Red Mirror",
    brand: "Ray-Ban",
    shape: "square",
    frame_type: "Full Rim",
    size_category: "Wide",
    material: "TR90 Rubber",
    price_inr: 6290,
    category: "sunglasses",
    gender: "men",
    color: "#e11d48",
    rating: 4.8,
    reviews_count: 17600,
    target_face_shapes: ["Round", "Oval"],
    image: "/frames/frame2.jpg",
    framePng: "/frames/jj-square-matte-navy-14.png",
    dimensions: { lens_width_mm: 55, bridge_width_mm: 16, temple_length_mm: 145, frame_width_mm: 144 }
  },
  {
    sku: "rayban_wayfarer_denimNoir_bleuMirroir",
    name: "Ray-Ban Wayfarer Denim Black / Blue Mirror",
    brand: "Ray-Ban",
    shape: "wayfarer",
    frame_type: "Full Rim",
    size_category: "Medium",
    material: "Genuine Denim Cloth & Acetate",
    price_inr: 7990,
    category: "sunglasses",
    gender: "unisex",
    color: "#1e3a8a",
    rating: 4.9,
    reviews_count: 8900,
    target_face_shapes: ["Round", "Oval", "Heart"],
    image: "/frames/frame3.jpg",
    framePng: "/frames/jj-wayfarer-crystal-blue-31.png",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 22, temple_length_mm: 150, frame_width_mm: 142 }
  },
  {
    sku: "rayban_aviator_gun_vert",
    name: "Ray-Ban Aviator Gunmetal Dark Green",
    brand: "Ray-Ban",
    shape: "aviator",
    frame_type: "Full Rim",
    size_category: "Wide",
    material: "Gunmetal Steel",
    price_inr: 7390,
    category: "sunglasses",
    gender: "men",
    color: "#334155",
    rating: 4.8,
    reviews_count: 22400,
    target_face_shapes: ["Square", "Heart", "Oval"],
    image: "/frames/frame4.jpg",
    framePng: "/frames/vc-aviator-black-pilot-22.png",
    dimensions: { lens_width_mm: 58, bridge_width_mm: 14, temple_length_mm: 140, frame_width_mm: 140 }
  }
];

const catalog = jeelizCatalog.map((item, index) => ({
  id: item.sku,
  ...item,
  image_path: item.image,
  frame_path: item.framePng
}));

fs.writeFileSync(path.resolve('src', 'data', 'frames.json'), JSON.stringify(catalog, null, 2), 'utf-8');
fs.writeFileSync(path.resolve('frames.json'), JSON.stringify(catalog, null, 2), 'utf-8');
console.log('✓ Successfully written official Jeeliz 3D glasses catalog to frames.json');
