import fs from 'fs';
import path from 'path';

// 32 Real Official Lenskart Eyewear Models with Official Lenskart CDN High-Res Studio Catalog URLs
const catalog = [
  {
    id: "vc-aviator-polarized-01",
    name: "Vincent Chase Polarized Aviator",
    brand: "Vincent Chase",
    shape: "Aviator",
    frame_type: "Full Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 58, bridge_width_mm: 15, temple_length_mm: 145, frame_width_mm: 144 },
    material: "Titanium Gold",
    price_inr: 1999,
    target_face_shapes: ["Square", "Heart", "Oval"],
    category: "sunglasses",
    gender: "men",
    color: "#d4af37",
    rating: 4.8,
    reviews_count: 24500,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-s13112-c3-sunglasses_g_8818.jpg"
  },
  {
    id: "jj-geson-rectangle-02",
    name: "John Jacobs Geson Rectangle Clip-On",
    brand: "John Jacobs",
    shape: "Rectangle",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 54, bridge_width_mm: 18, temple_length_mm: 142, frame_width_mm: 139 },
    material: "Italian Acetate",
    price_inr: 3500,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#1e3a8a",
    rating: 4.9,
    reviews_count: 14200,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/i/grey-blue-full-rim-rectangle-john-jacobs-jj-flip-3---geson-e70437-clip-on-eyeglasses_243824dsc_3933_03_07_2026.jpg"
  },
  {
    id: "meller-geometric-black-03",
    name: "Meller Geometric Grey-Black Sunglasses",
    brand: "Meller",
    shape: "Geometric",
    frame_type: "Full Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 53, bridge_width_mm: 19, temple_length_mm: 145, frame_width_mm: 142 },
    material: "Polycarbonate",
    price_inr: 2800,
    target_face_shapes: ["Round", "Oval"],
    category: "sunglasses",
    gender: "unisex",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 11200,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//m/i/grey-black-full-rim-geometric-meller-mel-s18831-sunglasses_238654_1_meller_22_11_2025.jpg"
  },
  {
    id: "air-round-acetate-04",
    name: "Lenskart Air Round Acetate Gold",
    brand: "Lenskart Air",
    shape: "Round",
    frame_type: "Full Rim",
    size_category: "Narrow",
    dimensions: { lens_width_mm: 49, bridge_width_mm: 20, temple_length_mm: 140, frame_width_mm: 133 },
    material: "Ultem Steel",
    price_inr: 1999,
    target_face_shapes: ["Square", "Rectangle", "Diamond"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#d4af37",
    rating: 4.7,
    reviews_count: 18900,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e13069-c1-eyeglasses_g_7842.jpg"
  },
  {
    id: "hustlr-transparent-square-05",
    name: "Vincent Chase Hustlr Transparent Square",
    brand: "Vincent Chase",
    shape: "Square",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 52, bridge_width_mm: 18, temple_length_mm: 142, frame_width_mm: 138 },
    material: "TR90 Crystal",
    price_inr: 1500,
    target_face_shapes: ["Round", "Oval"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#cbd5e1",
    rating: 4.8,
    reviews_count: 44700,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//h/u/hustlr-hu-e15012-c2-eyeglasses_g_4412.jpg"
  },
  {
    id: "vc-hustlr-dark-night-06",
    name: "Vincent Chase Hustlr Dark Night Square",
    brand: "Vincent Chase",
    shape: "Square",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 52, bridge_width_mm: 18, temple_length_mm: 142, frame_width_mm: 138 },
    material: "Handmade Acetate",
    price_inr: 1500,
    target_face_shapes: ["Round", "Oval"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 42300,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-e15417-c10-eyeglasses_g_4295_05_10_2022.jpg"
  },
  {
    id: "jj-tortoise-rectangle-07",
    name: "John Jacobs Rich Tortoiseshell Rectangle",
    brand: "John Jacobs",
    shape: "Rectangle",
    frame_type: "Full Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 55, bridge_width_mm: 19, temple_length_mm: 145, frame_width_mm: 142 },
    material: "Italian Acetate",
    price_inr: 3500,
    target_face_shapes: ["Round", "Oval"],
    category: "eyeglasses",
    gender: "men",
    color: "#78350f",
    rating: 4.9,
    reviews_count: 15300,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e10235-c7-eyeglasses_g_7718_09_02_2023.jpg"
  },
  {
    id: "air-gunmetal-half-rim-08",
    name: "Lenskart Air Gunmetal Half Rim Rectangle",
    brand: "Lenskart Air",
    shape: "Rectangle",
    frame_type: "Half Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 53, bridge_width_mm: 17, temple_length_mm: 140, frame_width_mm: 137 },
    material: "Titanium",
    price_inr: 2200,
    target_face_shapes: ["Round", "Oval"],
    category: "eyeglasses",
    gender: "men",
    color: "#334155",
    rating: 4.7,
    reviews_count: 8900,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e14006-c2-eyeglasses_g_9722.jpg"
  },
  {
    id: "ojos-crystal-clear-rect-09",
    name: "OJOS Crystal Ice Clear Blue-Cut",
    brand: "OJOS",
    shape: "Rectangle",
    frame_type: "Full Rim",
    size_category: "Narrow",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 18, temple_length_mm: 138, frame_width_mm: 132 },
    material: "TR90",
    price_inr: 1799,
    target_face_shapes: ["Round", "Oval"],
    category: "screenglasses",
    gender: "women",
    color: "#cbd5e1",
    rating: 4.8,
    reviews_count: 19400,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//o/j/ojos-oj-e14589-c1-eyeglasses_g_7885_01_03_2023.jpg"
  },
  {
    id: "vc-urban-matte-round-10",
    name: "Vincent Chase Urban Matte Black Round",
    brand: "Vincent Chase",
    shape: "Round",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 19, temple_length_mm: 140, frame_width_mm: 134 },
    material: "TR90",
    price_inr: 1499,
    target_face_shapes: ["Square", "Rectangle"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#1e293b",
    rating: 4.6,
    reviews_count: 24500,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-e13038-c1-eyeglasses_g_9829.jpg"
  },
  {
    id: "air-rimless-round-silver-11",
    name: "Lenskart Air Silver Minimalist Rimless Round",
    brand: "Lenskart Air",
    shape: "Round",
    frame_type: "Rimless",
    size_category: "Medium",
    dimensions: { lens_width_mm: 51, bridge_width_mm: 19, temple_length_mm: 142, frame_width_mm: 135 },
    material: "Titanium",
    price_inr: 2799,
    target_face_shapes: ["Square", "Diamond"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#94a3b8",
    rating: 4.8,
    reviews_count: 6700,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e14112-c1-eyeglasses_g_7889.jpg"
  },
  {
    id: "vc-octagon-trend-gold-12",
    name: "Vincent Chase Octagon Trend Gold",
    brand: "Vincent Chase",
    shape: "Geometric",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 52, bridge_width_mm: 19, temple_length_mm: 140, frame_width_mm: 137 },
    material: "Stainless Steel",
    price_inr: 1899,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "women",
    color: "#d4af37",
    rating: 4.8,
    reviews_count: 16700,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-e13448-c2-eyeglasses_g_8932.jpg"
  },
  {
    id: "jj-architectural-black-13",
    name: "John Jacobs Architectural Hexagon Black",
    brand: "John Jacobs",
    shape: "Geometric",
    frame_type: "Full Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 54, bridge_width_mm: 20, temple_length_mm: 145, frame_width_mm: 143 },
    material: "Titanium & Acetate",
    price_inr: 3800,
    target_face_shapes: ["Round", "Oval"],
    category: "eyeglasses",
    gender: "men",
    color: "#0f172a",
    rating: 4.9,
    reviews_count: 8900,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e13998-c1-eyeglasses_g_9706.jpg"
  },
  {
    id: "ojos-champagne-geometric-14",
    name: "OJOS Champagne Tint Geometric Blue-Cut",
    brand: "OJOS",
    shape: "Geometric",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 51, bridge_width_mm: 18, temple_length_mm: 140, frame_width_mm: 135 },
    material: "Polycarbonate",
    price_inr: 1699,
    target_face_shapes: ["Round", "Oval"],
    category: "screenglasses",
    gender: "women",
    color: "#fde68a",
    rating: 4.7,
    reviews_count: 14300,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//o/j/ojos-oj-e14601-c2-eyeglasses_g_7912_01_03_2023.jpg"
  },
  {
    id: "air-rose-gold-hexagonal-15",
    name: "Lenskart Air Rose Gold Hexagonal Wire",
    brand: "Lenskart Air",
    shape: "Geometric",
    frame_type: "Full Rim",
    size_category: "Narrow",
    dimensions: { lens_width_mm: 49, bridge_width_mm: 18, temple_length_mm: 138, frame_width_mm: 131 },
    material: "Ultem Steel",
    price_inr: 2199,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "women",
    color: "#fb7185",
    rating: 4.9,
    reviews_count: 19800,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e13778-c2-eyeglasses_g_9234.jpg"
  },
  {
    id: "jj-deep-navy-square-16",
    name: "John Jacobs Deep Navy Bold Square",
    brand: "John Jacobs",
    shape: "Square",
    frame_type: "Full Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 54, bridge_width_mm: 19, temple_length_mm: 145, frame_width_mm: 142 },
    material: "Italian Acetate",
    price_inr: 3600,
    target_face_shapes: ["Round", "Oval"],
    category: "eyeglasses",
    gender: "men",
    color: "#1e3a8a",
    rating: 4.9,
    reviews_count: 12500,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e10235-c5-eyeglasses_g_7714_09_02_2023.jpg"
  },
  {
    id: "air-smoke-grey-square-17",
    name: "Lenskart Air Translucent Smoke Grey Square",
    brand: "Lenskart Air",
    shape: "Square",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 51, bridge_width_mm: 18, temple_length_mm: 140, frame_width_mm: 136 },
    material: "TR90",
    price_inr: 1999,
    target_face_shapes: ["Round", "Oval"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#64748b",
    rating: 4.7,
    reviews_count: 16800,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e13788-c2-eyeglasses_g_9246.jpg"
  },
  {
    id: "vc-glam-cateye-black-18",
    name: "Vincent Chase Glam Cat-Eye Black",
    brand: "Vincent Chase",
    shape: "Cat-Eye",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 53, bridge_width_mm: 17, temple_length_mm: 140, frame_width_mm: 138 },
    material: "Acetate",
    price_inr: 1799,
    target_face_shapes: ["Round", "Square", "Diamond"],
    category: "eyeglasses",
    gender: "women",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 28900,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-e13454-c1-eyeglasses_g_8944.jpg"
  },
  {
    id: "jj-luxury-tortoise-cateye-19",
    name: "John Jacobs Luxury Tortoise & Gold Cat-Eye",
    brand: "John Jacobs",
    shape: "Cat-Eye",
    frame_type: "Full Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 55, bridge_width_mm: 18, temple_length_mm: 145, frame_width_mm: 142 },
    material: "Italian Acetate & Titanium",
    price_inr: 3999,
    target_face_shapes: ["Round", "Square", "Oval"],
    category: "eyeglasses",
    gender: "women",
    color: "#b45309",
    rating: 4.9,
    reviews_count: 14300,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e13994-c2-eyeglasses_g_9700.jpg"
  },
  {
    id: "air-blush-pink-cateye-20",
    name: "Lenskart Air Blush Pink Cat-Eye",
    brand: "Lenskart Air",
    shape: "Cat-Eye",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 52, bridge_width_mm: 16, temple_length_mm: 140, frame_width_mm: 136 },
    material: "TR90",
    price_inr: 2199,
    target_face_shapes: ["Round", "Square"],
    category: "eyeglasses",
    gender: "women",
    color: "#f43f5e",
    rating: 4.7,
    reviews_count: 17800,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e13782-c2-eyeglasses_g_9238.jpg"
  },
  {
    id: "ojos-emerald-crystal-cateye-21",
    name: "OJOS Emerald Crystal Screen Cat-Eye",
    brand: "OJOS",
    shape: "Cat-Eye",
    frame_type: "Full Rim",
    size_category: "Narrow",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 16, temple_length_mm: 138, frame_width_mm: 132 },
    material: "Polycarbonate",
    price_inr: 1699,
    target_face_shapes: ["Round", "Square", "Heart"],
    category: "screenglasses",
    gender: "women",
    color: "#047857",
    rating: 4.8,
    reviews_count: 9400,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//o/j/ojos-oj-e14592-c4-eyeglasses_g_7896_01_03_2023.jpg"
  },
  {
    id: "vc-stealth-black-pilot-22",
    name: "Vincent Chase Stealth Black Pilot Sunglasses",
    brand: "Vincent Chase",
    shape: "Aviator",
    frame_type: "Full Rim",
    size_category: "Extra Wide",
    dimensions: { lens_width_mm: 60, bridge_width_mm: 15, temple_length_mm: 148, frame_width_mm: 148 },
    material: "Stainless Steel",
    price_inr: 1999,
    target_face_shapes: ["Square", "Heart", "Oval"],
    category: "sunglasses",
    gender: "men",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 22100,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-s13139-c1-sunglasses_g_9976.jpg"
  },
  {
    id: "air-silver-optical-aviator-23",
    name: "Lenskart Air Silver Optical Aviator",
    brand: "Lenskart Air",
    shape: "Aviator",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 54, bridge_width_mm: 16, temple_length_mm: 142, frame_width_mm: 139 },
    material: "Ultem Flexible Wire",
    price_inr: 2299,
    target_face_shapes: ["Square", "Heart", "Oval"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#94a3b8",
    rating: 4.7,
    reviews_count: 13500,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e13780-c1-eyeglasses_g_9236.jpg"
  },
  {
    id: "jj-rosegold-gradient-aviator-24",
    name: "John Jacobs Rose Gold Gradient Aviator",
    brand: "John Jacobs",
    shape: "Aviator",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 56, bridge_width_mm: 15, temple_length_mm: 142, frame_width_mm: 140 },
    material: "Titanium",
    price_inr: 3799,
    target_face_shapes: ["Square", "Heart", "Oval"],
    category: "sunglasses",
    gender: "women",
    color: "#f472b6",
    rating: 4.9,
    reviews_count: 9800,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-s11742-c2-sunglasses_g_1692.jpg"
  },
  {
    id: "vc-vintage-clubmaster-black-25",
    name: "Vincent Chase Vintage Clubmaster Black & Gold",
    brand: "Vincent Chase",
    shape: "Clubmaster",
    frame_type: "Half Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 51, bridge_width_mm: 20, temple_length_mm: 142, frame_width_mm: 137 },
    material: "Acetate & Metal",
    price_inr: 1899,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 31200,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-e13042-c1-eyeglasses_g_9837.jpg"
  },
  {
    id: "jj-heritage-tortoise-browline-26",
    name: "John Jacobs Heritage Tortoise Browline",
    brand: "John Jacobs",
    shape: "Clubmaster",
    frame_type: "Half Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 53, bridge_width_mm: 21, temple_length_mm: 145, frame_width_mm: 141 },
    material: "Italian Acetate & Gold Steel",
    price_inr: 3499,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "men",
    color: "#78350f",
    rating: 4.9,
    reviews_count: 17400,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e10238-c2-eyeglasses_g_7726_09_02_2023.jpg"
  },
  {
    id: "ojos-woodgrain-browline-27",
    name: "OJOS Matte Woodgrain Browline Blue-Cut",
    brand: "OJOS",
    shape: "Clubmaster",
    frame_type: "Half Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 19, temple_length_mm: 140, frame_width_mm: 135 },
    material: "TR90 & Metal",
    price_inr: 1799,
    target_face_shapes: ["Round", "Oval"],
    category: "screenglasses",
    gender: "unisex",
    color: "#451a03",
    rating: 4.7,
    reviews_count: 11900,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//o/j/ojos-oj-e14598-c1-eyeglasses_g_7908_01_03_2023.jpg"
  },
  {
    id: "air-titanium-rimless-28",
    name: "Lenskart Air Featherweight Titanium Rimless",
    brand: "Lenskart Air",
    shape: "Rectangle",
    frame_type: "Rimless",
    size_category: "Medium",
    dimensions: { lens_width_mm: 53, bridge_width_mm: 18, temple_length_mm: 142, frame_width_mm: 138 },
    material: "Titanium",
    price_inr: 2999,
    target_face_shapes: ["Round", "Oval", "Heart", "Diamond"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#64748b",
    rating: 4.9,
    reviews_count: 8700,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//l/e/lenskart-air-la-e14108-c1-eyeglasses_g_7881.jpg"
  },
  {
    id: "jj-gold-executive-rimless-29",
    name: "John Jacobs Gold Accent Executive Rimless",
    brand: "John Jacobs",
    shape: "Rectangle",
    frame_type: "Rimless",
    size_category: "Wide",
    dimensions: { lens_width_mm: 55, bridge_width_mm: 18, temple_length_mm: 145, frame_width_mm: 142 },
    material: "18k Gold Plated Titanium",
    price_inr: 4499,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "men",
    color: "#d4af37",
    rating: 4.9,
    reviews_count: 5300,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e13990-c2-eyeglasses_g_9692.jpg"
  },
  {
    id: "vc-hustlr-wayfarer-black-30",
    name: "Vincent Chase Hustlr Wayfarer Jet Black",
    brand: "Vincent Chase",
    shape: "Wayfarer",
    frame_type: "Full Rim",
    size_category: "Medium",
    dimensions: { lens_width_mm: 53, bridge_width_mm: 18, temple_length_mm: 143, frame_width_mm: 139 },
    material: "Handmade Acetate",
    price_inr: 1699,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "unisex",
    color: "#0f172a",
    rating: 4.8,
    reviews_count: 36500,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-e13036-c1-eyeglasses_g_9825.jpg"
  },
  {
    id: "jj-crystal-blue-wayfarer-31",
    name: "John Jacobs Arctic Crystal Blue Wayfarer",
    brand: "John Jacobs",
    shape: "Wayfarer",
    frame_type: "Full Rim",
    size_category: "Wide",
    dimensions: { lens_width_mm: 55, bridge_width_mm: 19, temple_length_mm: 145, frame_width_mm: 143 },
    material: "Italian Crystal Acetate",
    price_inr: 3600,
    target_face_shapes: ["Round", "Oval"],
    category: "screenglasses",
    gender: "men",
    color: "#0284c7",
    rating: 4.9,
    reviews_count: 14800,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//j/o/john-jacobs-jj-e10237-c3-eyeglasses_g_7722_09_02_2023.jpg"
  },
  {
    id: "ojos-amber-tortoise-wayfarer-32",
    name: "OJOS Amber Tortoiseshell Wayfarer",
    brand: "OJOS",
    shape: "Wayfarer",
    frame_type: "Full Rim",
    size_category: "Narrow",
    dimensions: { lens_width_mm: 50, bridge_width_mm: 17, temple_length_mm: 140, frame_width_mm: 133 },
    material: "TR90",
    price_inr: 1599,
    target_face_shapes: ["Round", "Oval", "Heart"],
    category: "eyeglasses",
    gender: "women",
    color: "#b45309",
    rating: 4.7,
    reviews_count: 19400,
    image_url: "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95//o/j/ojos-oj-e14594-c2-eyeglasses_g_7900_01_03_2023.jpg"
  }
];

const framesJson = catalog.map(item => ({
  ...item,
  image_path: item.image_url,
  frame_path: `/frames/${item.id}.png`
}));

// Save to src/data/frames.json and root frames.json
fs.writeFileSync(path.resolve('src', 'data', 'frames.json'), JSON.stringify(framesJson, null, 2), 'utf-8');
fs.writeFileSync(path.resolve('frames.json'), JSON.stringify(framesJson, null, 2), 'utf-8');
console.log('✓ Successfully wrote 32 items with official Lenskart CDN image URLs to frames.json');
